In [2]:
import numpy as np
import tensorflow as tf
print("PACKAGES LOADED")

PACKAGES LOADED


In [3]:
def print_tf(x):
    print("TYPE IS\n %s" %(type(x)))
    print("VALUE IS\n %s" % x)

hello = tf.constant("HELLO. IT'S ME")
print_tf(hello.numpy())

TYPE IS
 <class 'bytes'>
VALUE IS
 b"HELLO. IT'S ME"


In [4]:
a=tf.constant(1.5)
b=tf.constant(2.5)

print_tf(a)
print_tf(b)
print_tf(a.numpy())
print_tf(b.numpy())

TYPE IS
 <class 'tensorflow.python.framework.ops.EagerTensor'>
VALUE IS
 tf.Tensor(1.5, shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.EagerTensor'>
VALUE IS
 tf.Tensor(2.5, shape=(), dtype=float32)
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


In [5]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)
print_tf(a_plus_b.numpy())

TYPE IS
 <class 'tensorflow.python.framework.ops.EagerTensor'>
VALUE IS
 tf.Tensor(4.0, shape=(), dtype=float32)
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [8]:
a_mul_b=tf.multiply(a, b);
print_tf(a_mul_b)
print_tf(a_mul_b.numpy())

TYPE IS
 <class 'tensorflow.python.framework.ops.EagerTensor'>
VALUE IS
 tf.Tensor(3.75, shape=(), dtype=float32)
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


In [14]:
weight = tf.Variable(tf.random.normal([5, 2], stddev=0.1))
print_tf(weight)
print_tf(weight.numpy())

TYPE IS
 <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.10631603,  0.05958499],
       [ 0.13267592, -0.04230813],
       [-0.10196169,  0.08641391],
       [ 0.0229465 ,  0.11084868],
       [-0.13997196, -0.10482349]], dtype=float32)>
TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.10631603  0.05958499]
 [ 0.13267592 -0.04230813]
 [-0.10196169  0.08641391]
 [ 0.0229465   0.11084868]
 [-0.13997196 -0.10482349]]


In [31]:
def oper(x):
    return tf.matmul(x, weight)

x = np.random.rand(10, 5).astype(np.float32);

print_tf(oper(x));
print_tf(oper(x).numpy());

TYPE IS
 <class 'tensorflow.python.framework.ops.EagerTensor'>
VALUE IS
 tf.Tensor(
[[ 0.04315891  0.02566545]
 [ 0.0662707   0.08727598]
 [-0.03449424  0.10770884]
 [ 0.15880866  0.05846872]
 [ 0.04275899  0.08053295]
 [-0.05045326 -0.03375901]
 [ 0.06329519  0.12624145]
 [ 0.14224364  0.00183705]
 [ 0.03962988  0.05526929]
 [-0.08933797 -0.03636008]], shape=(10, 2), dtype=float32)
TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.04315891  0.02566545]
 [ 0.0662707   0.08727598]
 [-0.03449424  0.10770884]
 [ 0.15880866  0.05846872]
 [ 0.04275899  0.08053295]
 [-0.05045326 -0.03375901]
 [ 0.06329519  0.12624145]
 [ 0.14224364  0.00183705]
 [ 0.03962988  0.05526929]
 [-0.08933797 -0.03636008]]
